### PR TITLE
add new nlp folder stac_wrapper

### PR DESCRIPTION
**Pull request by ChaamC**
PR that simply adds the nlp folder 'stac_wrapper'

### CODE REVIEW

**Comment by dbyrns** [comment]
LGTM. The notebooks include the output cells, I don't know @reboutli-crim if you would prefer them to be removed?

**Comment by reboutli-crim** [comment]
Thank you @ChaamC  and @dbyrns. Yes I would prefer the output celle to be removed,

**Comment by ChaamC** [comment]
Notebook outputs removed! 
Let me know if it's okay to merge now.

**Review by reboutli-crim — COMMENTED** [review]
These notebooks are still drafts. I will remove French texts and to add comments on what they are supposed to do before merging them.

**Review by reboutli-crim — APPROVED** [review]

**Review by dbyrns — APPROVED** [review]
LGTM

**Comment by ChaamC** [comment]
@reboutli-crim 
To be sure before merging, the `Sandbox. DAC-315,320.ipynb` notebook has some cell outputs, is it intentional?

**Comment by reboutli-crim** [comment]
> 

No, there should not be any cell outputs. Can you delete them before merging? Thank you!

**Comment by ChaamC** [comment]
Perfect, I'll remove the remaining outputs and proceed to merge! :)

**Comment by ChaamC** [comment]
My bad, seems the output was already cleared, I thinked I looked at the wrong diff earlier! Proceeding with merge...

**Pull request merged**
